---
version: 2.1

jobs:
  validator:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run: bash tools/format.sh

workflows:
  version: 2
  validation:
    jobs:
      - validator:
          context:
            - token
