name: Json Formatter

on:
  push:
    paths:
      - '*.json'
      - '**/*.json'
  pull_request:

env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

jobs:
  format:
    environment: TELEGRAM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Format json
        run: bash tools/format.sh

      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          branch: ${{ github.ref }}
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
