name: Json Formatter

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Validate Json
        run: python tools/validate.py

      - name: Format json
        run: bash tools/format.sh

      - name: Commit Changes
        run: "git commit -am '[Hycon-CI]: json autoformat'"
        continue-on-error: true

      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}