name: Lint Code Base

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          VALIDATE_JSON: true
          LOG_LEVEL: WARN
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}